FROM debian:9.3
MAINTAINER Konstantin Martini <konstantin@martini.pm>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y python-pip librabbitmq4
RUN apt-get install -y vim tmux

ADD celery_app/requirements.txt /
RUN pip install -r requirements.txt

ADD celery-app/code /code
WORKDIR /code

ENV CELERY_APP celery_app

CMD ["celery", "worker", "--loglevel", "info"]
