---
version: '3'

services:

  commander:
    container_name: commander
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.commander
    links:
      - redis
      - rabbit
      #- postgres

  worker:
    container_name: worker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.worker
    links:
      - redis
      - rabbit
      #- postgres

  redis:
    image: redis:4.0.6
    restart: always

  rabbit:
    image: rabbitmq:3.7.1
    restart: always

# postgres result backend not yet in use
  #postgres:
    #image: postgres
    #restart: always
    #environment:
      #POSTGRES_PASSWORD: test
